# Example of values.
#bu: bu
#environment: env
#projectname: PROJECT_NAME
#applicationrole: APP_NAME
#
#replicaCount: replicaCount
#namespace: NAMESPACE
#managedIdentityClientId: WORKLOAD_ID_CLIENT_ID
#image: ACR_IMAGE
#pullPolicy: IfNotPresent
#containerPort: containerPort
#livenessProbe:
#  path: /health
#  port: "80"
#  initialDelaySeconds: "10"
#  periodSeconds: "10"
#readinessProbe:
#  path: /health
#  port: "80"
#  initialDelaySeconds: "10"
#  periodSeconds: "10"
#env:
#  - name: env1
#    value: value1
#  - name: env2
#    value: value2
#resources: 
#  limits:
#    cpu: xxxm
#    memory: xxxMi
#  requests:
#    cpu: xxm
#    memory: xxMi
#nodeSelector: {}
#tolerations: []
#affinity: {}
#service:
#  port: PORT
#
#
# Ingress:
#
#ingress:
#  enabled: false
#or
#ingress:
#  enabled: true
#  annotations:  # Customizable annotations by application
#    appgw.ingress.kubernetes.io/use-private-ip: "true" #only if ingress is internal
#    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
#  hosts:
#    - host: xxxxxxx.azure.jmfamily.com
#      paths:
#        - path: /app
#          pathType: Exact
#
#
# Network Policy North-South (if inboundPolicyNorthSouth = true in namespace level):
#
#inboundPolicyNorthSouth:
#  enabled: false
#or
#inboundPolicyNorthSouth:
#  enabled: true
#  publisherLabel: NS-PROJECT_NAME
#
#
# App Configuration: This provider should be used only if the workload pod can't use workload identity and MSAL sdk to directly access the target app config store
#
#appconfig:
#  enabled: false
#or
#appconfig:
#  enabled: true
#  endpoint: https://xxxxxxxxxx.azconfig.io
#  settingsfile: settings.json
#  settingsfilepath: /app/config
#  keyprefix: set.awcps.warrantyclaim*
#  keyprefixsentinel: set.awcps.warrantyclaim.Sentinel
#env:
#  - name: DOTNET_USE_POLLING_FILE_WATCHER
#    value: "true"