apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    azure.workload.identity/use: "true"
  {{- if .Values.inboundPolicyNorthSouth.enabled }}
    app.kubernetes.io/inbound-ns-publisher: {{ .Values.inboundPolicyNorthSouth.publisherLabel }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app:  {{ template "app.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        azure.workload.identity/use: "true"
      {{- if .Values.inboundPolicyNorthSouth.enabled }}
        app.kubernetes.io/inbound-ns-publisher: {{ .Values.inboundPolicyNorthSouth.publisherLabel }}
      {{- end }}
    spec:
      serviceAccountName: {{ template "serviceaccountname" . }}
      containers:
      - name: {{ template "app.name" . }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.containerPort }}
            protocol: TCP
      {{- if .Values.livenessProbe }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.livenessProbe.port }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
      {{- end }}
      {{- if .Values.readinessProbe }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.readinessProbe.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
      {{- end }}
      {{- if .Values.appconfig.enabled }}
        volumeMounts:
        - name: {{ template "app.name.appconfig" . }}-vol 
          mountPath: {{ .Values.appconfig.settingsfilepath }}
      {{- end }}
      {{- if .Values.env }}
        env:
          {{- range .Values.env }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end }}
      {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
    {{- if .Values.appconfig.enabled }}
      volumes:
      - name: {{ template "app.name.appconfig" . }}-vol
        configMap: 
          name: {{ template "app.name.appconfig" . }}-configmap
    {{- end }}
    {{- with .Values.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- with .Values.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
  {{- end }}