{{- if .Values.inboundPolicyEastWest.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-eastwest-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from: 
    - podSelector: {}
    - ipBlock:
        cidr: {{ .Values.inboundPolicyEastWest.NodeSubnetcidr }}
{{- end }}