name: Helm Chart template
run-name: Helm Chart template 🚀 ${{ inputs.Environment }}

on:
  workflow_dispatch:
    inputs:
      Environment:
        type: choice
        description: 'Environment'
        required: true
        options: 
           - dev
           - stg
           - uat

permissions:
  id-token: write
  contents: write

jobs:
  
  helm-chart-package:
    runs-on: ubuntu-latest
    environment: ${{ inputs.Environment }}

    steps:

    # Checkout code
    - uses: actions/checkout@v3

    # Log into Azure
    - name: Az CLI login
      uses: azure/login@v1
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        
    - name: Login to Azure Container Registry
      run: |
        az acr login --name ${{ vars.REGISTRY_NAME }}

    - name: Application Helm chart - package
      run: |
        cd helm/application
        helm package . -d charts/
      
    - name: Push Application template - ACR OCI artifacts
      run: |
        helm push $(ls -t helm/application/charts/*.tgz | head -n1) oci://${{ vars.REGISTRY_NAME }}.azurecr.io/helm

    - name: Namespace Helm chart - package
      run: |
        cd helm/namespace
        helm package . -d charts/
      
    - name: Push Namespace template - ACR OCI artifacts
      run: |
        helm push $(ls -t helm/namespace/charts/*.tgz | head -n1) oci://${{ vars.REGISTRY_NAME }}.azurecr.io/helm